### PR TITLE
carStream: Improve local file browser design

### PR DESCRIPTION
**Pull request by danielstuart14**
Sets it with the color scheme from the app.
Also, this commit fixes the "version report" spacing in the app header

After

### CODE REVIEW

**Comment by thekirankumar** [comment]
Awesome

**Comment by thekirankumar** [comment]
Will merged once Travis reports success

**Comment by thekirankumar** [comment]
Thanks Daniel, this was pretty cool and a much required feature

**Comment by danielstuart14** [comment]
Glad to hear! I'm looking into localizing the file browser java script, but I'm not that familiar with JS.
I'll keep searching for a pratical way of doing that.

**Comment by thekirankumar** [comment]
Me too, not very comfortable with JS. Thanks for the help again.

**Pull request merged**
